// @generated by scripts/generate_sig_algorithms.py
// Source: oqs-sys/liboqs/src/sig/sig.h
// Do not edit manually.

implement_sigs! {
    ("ml_dsa") MlDsa44: OQS_SIG_alg_ml_dsa_44,
    ("ml_dsa") MlDsa65: OQS_SIG_alg_ml_dsa_65,
    ("ml_dsa") MlDsa87: OQS_SIG_alg_ml_dsa_87,
    ("falcon") Falcon512: OQS_SIG_alg_falcon_512,
    ("falcon") Falcon1024: OQS_SIG_alg_falcon_1024,
    ("falcon") FalconPadded512: OQS_SIG_alg_falcon_padded_512,
    ("falcon") FalconPadded1024: OQS_SIG_alg_falcon_padded_1024,
    ("mayo") Mayo1: OQS_SIG_alg_mayo_1,
    ("mayo") Mayo2: OQS_SIG_alg_mayo_2,
    ("mayo") Mayo3: OQS_SIG_alg_mayo_3,
    ("mayo") Mayo5: OQS_SIG_alg_mayo_5,
    ("cross") CrossRsdp128Balanced: OQS_SIG_alg_cross_rsdp_128_balanced,
    ("cross") CrossRsdp128Fast: OQS_SIG_alg_cross_rsdp_128_fast,
    ("cross") CrossRsdp128Small: OQS_SIG_alg_cross_rsdp_128_small,
    ("cross") CrossRsdp192Balanced: OQS_SIG_alg_cross_rsdp_192_balanced,
    ("cross") CrossRsdp192Fast: OQS_SIG_alg_cross_rsdp_192_fast,
    ("cross") CrossRsdp192Small: OQS_SIG_alg_cross_rsdp_192_small,
    ("cross") CrossRsdp256Balanced: OQS_SIG_alg_cross_rsdp_256_balanced,
    ("cross") CrossRsdp256Fast: OQS_SIG_alg_cross_rsdp_256_fast,
    ("cross") CrossRsdp256Small: OQS_SIG_alg_cross_rsdp_256_small,
    ("cross") CrossRsdpg128Balanced: OQS_SIG_alg_cross_rsdpg_128_balanced,
    ("cross") CrossRsdpg128Fast: OQS_SIG_alg_cross_rsdpg_128_fast,
    ("cross") CrossRsdpg128Small: OQS_SIG_alg_cross_rsdpg_128_small,
    ("cross") CrossRsdpg192Balanced: OQS_SIG_alg_cross_rsdpg_192_balanced,
    ("cross") CrossRsdpg192Fast: OQS_SIG_alg_cross_rsdpg_192_fast,
    ("cross") CrossRsdpg192Small: OQS_SIG_alg_cross_rsdpg_192_small,
    ("cross") CrossRsdpg256Balanced: OQS_SIG_alg_cross_rsdpg_256_balanced,
    ("cross") CrossRsdpg256Fast: OQS_SIG_alg_cross_rsdpg_256_fast,
    ("cross") CrossRsdpg256Small: OQS_SIG_alg_cross_rsdpg_256_small,
    ("uov") UovOvIs: OQS_SIG_alg_uov_ov_Is,
    ("uov") UovOvIp: OQS_SIG_alg_uov_ov_Ip,
    ("uov") UovOvIII: OQS_SIG_alg_uov_ov_III,
    ("uov") UovOvV: OQS_SIG_alg_uov_ov_V,
    ("uov") UovOvIsPkc: OQS_SIG_alg_uov_ov_Is_pkc,
    ("uov") UovOvIpPkc: OQS_SIG_alg_uov_ov_Ip_pkc,
    ("uov") UovOvIIIPkc: OQS_SIG_alg_uov_ov_III_pkc,
    ("uov") UovOvVPkc: OQS_SIG_alg_uov_ov_V_pkc,
    ("uov") UovOvIsPkcSkc: OQS_SIG_alg_uov_ov_Is_pkc_skc,
    ("uov") UovOvIpPkcSkc: OQS_SIG_alg_uov_ov_Ip_pkc_skc,
    ("uov") UovOvIIIPkcSkc: OQS_SIG_alg_uov_ov_III_pkc_skc,
    ("uov") UovOvVPkcSkc: OQS_SIG_alg_uov_ov_V_pkc_skc,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaPureSha2128s: OQS_SIG_alg_slh_dsa_pure_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaPureSha2128f: OQS_SIG_alg_slh_dsa_pure_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaPureSha2192s: OQS_SIG_alg_slh_dsa_pure_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaPureSha2192f: OQS_SIG_alg_slh_dsa_pure_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaPureSha2256s: OQS_SIG_alg_slh_dsa_pure_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaPureSha2256f: OQS_SIG_alg_slh_dsa_pure_sha2_256f,
    ("slh_dsa") SlhDsaPureShake128s: OQS_SIG_alg_slh_dsa_pure_shake_128s,
    ("slh_dsa") SlhDsaPureShake128f: OQS_SIG_alg_slh_dsa_pure_shake_128f,
    ("slh_dsa") SlhDsaPureShake192s: OQS_SIG_alg_slh_dsa_pure_shake_192s,
    ("slh_dsa") SlhDsaPureShake192f: OQS_SIG_alg_slh_dsa_pure_shake_192f,
    ("slh_dsa") SlhDsaPureShake256s: OQS_SIG_alg_slh_dsa_pure_shake_256s,
    ("slh_dsa") SlhDsaPureShake256f: OQS_SIG_alg_slh_dsa_pure_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2224PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha2_224_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2224PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha2_224_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2224PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha2_224_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2224PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha2_224_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2224PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha2_224_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2224PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha2_224_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha2224PrehashShake128s: OQS_SIG_alg_slh_dsa_sha2_224_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha2224PrehashShake128f: OQS_SIG_alg_slh_dsa_sha2_224_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha2224PrehashShake192s: OQS_SIG_alg_slh_dsa_sha2_224_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha2224PrehashShake192f: OQS_SIG_alg_slh_dsa_sha2_224_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha2224PrehashShake256s: OQS_SIG_alg_slh_dsa_sha2_224_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha2224PrehashShake256f: OQS_SIG_alg_slh_dsa_sha2_224_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2256PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha2_256_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2256PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha2_256_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2256PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha2_256_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2256PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha2_256_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2256PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha2_256_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2256PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha2_256_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha2256PrehashShake128s: OQS_SIG_alg_slh_dsa_sha2_256_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha2256PrehashShake128f: OQS_SIG_alg_slh_dsa_sha2_256_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha2256PrehashShake192s: OQS_SIG_alg_slh_dsa_sha2_256_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha2256PrehashShake192f: OQS_SIG_alg_slh_dsa_sha2_256_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha2256PrehashShake256s: OQS_SIG_alg_slh_dsa_sha2_256_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha2256PrehashShake256f: OQS_SIG_alg_slh_dsa_sha2_256_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2384PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha2_384_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2384PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha2_384_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2384PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha2_384_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2384PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha2_384_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2384PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha2_384_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2384PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha2_384_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha2384PrehashShake128s: OQS_SIG_alg_slh_dsa_sha2_384_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha2384PrehashShake128f: OQS_SIG_alg_slh_dsa_sha2_384_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha2384PrehashShake192s: OQS_SIG_alg_slh_dsa_sha2_384_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha2384PrehashShake192f: OQS_SIG_alg_slh_dsa_sha2_384_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha2384PrehashShake256s: OQS_SIG_alg_slh_dsa_sha2_384_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha2384PrehashShake256f: OQS_SIG_alg_slh_dsa_sha2_384_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha2_512_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha2_512_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha2_512_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha2_512_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha2_512_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha2_512_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha2512PrehashShake128s: OQS_SIG_alg_slh_dsa_sha2_512_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha2512PrehashShake128f: OQS_SIG_alg_slh_dsa_sha2_512_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha2512PrehashShake192s: OQS_SIG_alg_slh_dsa_sha2_512_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha2512PrehashShake192f: OQS_SIG_alg_slh_dsa_sha2_512_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha2512PrehashShake256s: OQS_SIG_alg_slh_dsa_sha2_512_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha2512PrehashShake256f: OQS_SIG_alg_slh_dsa_sha2_512_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512224PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512224PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512224PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512224PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512224PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512224PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha2512224PrehashShake128s: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha2512224PrehashShake128f: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha2512224PrehashShake192s: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha2512224PrehashShake192f: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha2512224PrehashShake256s: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha2512224PrehashShake256f: OQS_SIG_alg_slh_dsa_sha2_512_224_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512256PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512256PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512256PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512256PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512256PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha2512256PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha2512256PrehashShake128s: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha2512256PrehashShake128f: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha2512256PrehashShake192s: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha2512256PrehashShake192f: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha2512256PrehashShake256s: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha2512256PrehashShake256f: OQS_SIG_alg_slh_dsa_sha2_512_256_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3224PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha3_224_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3224PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha3_224_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3224PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha3_224_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3224PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha3_224_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3224PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha3_224_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3224PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha3_224_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha3224PrehashShake128s: OQS_SIG_alg_slh_dsa_sha3_224_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha3224PrehashShake128f: OQS_SIG_alg_slh_dsa_sha3_224_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha3224PrehashShake192s: OQS_SIG_alg_slh_dsa_sha3_224_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha3224PrehashShake192f: OQS_SIG_alg_slh_dsa_sha3_224_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha3224PrehashShake256s: OQS_SIG_alg_slh_dsa_sha3_224_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha3224PrehashShake256f: OQS_SIG_alg_slh_dsa_sha3_224_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3256PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha3_256_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3256PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha3_256_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3256PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha3_256_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3256PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha3_256_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3256PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha3_256_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3256PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha3_256_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha3256PrehashShake128s: OQS_SIG_alg_slh_dsa_sha3_256_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha3256PrehashShake128f: OQS_SIG_alg_slh_dsa_sha3_256_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha3256PrehashShake192s: OQS_SIG_alg_slh_dsa_sha3_256_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha3256PrehashShake192f: OQS_SIG_alg_slh_dsa_sha3_256_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha3256PrehashShake256s: OQS_SIG_alg_slh_dsa_sha3_256_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha3256PrehashShake256f: OQS_SIG_alg_slh_dsa_sha3_256_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3384PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha3_384_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3384PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha3_384_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3384PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha3_384_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3384PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha3_384_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3384PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha3_384_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3384PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha3_384_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha3384PrehashShake128s: OQS_SIG_alg_slh_dsa_sha3_384_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha3384PrehashShake128f: OQS_SIG_alg_slh_dsa_sha3_384_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha3384PrehashShake192s: OQS_SIG_alg_slh_dsa_sha3_384_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha3384PrehashShake192f: OQS_SIG_alg_slh_dsa_sha3_384_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha3384PrehashShake256s: OQS_SIG_alg_slh_dsa_sha3_384_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha3384PrehashShake256f: OQS_SIG_alg_slh_dsa_sha3_384_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3512PrehashSha2128s: OQS_SIG_alg_slh_dsa_sha3_512_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3512PrehashSha2128f: OQS_SIG_alg_slh_dsa_sha3_512_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3512PrehashSha2192s: OQS_SIG_alg_slh_dsa_sha3_512_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3512PrehashSha2192f: OQS_SIG_alg_slh_dsa_sha3_512_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3512PrehashSha2256s: OQS_SIG_alg_slh_dsa_sha3_512_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaSha3512PrehashSha2256f: OQS_SIG_alg_slh_dsa_sha3_512_prehash_sha2_256f,
    ("slh_dsa") SlhDsaSha3512PrehashShake128s: OQS_SIG_alg_slh_dsa_sha3_512_prehash_shake_128s,
    ("slh_dsa") SlhDsaSha3512PrehashShake128f: OQS_SIG_alg_slh_dsa_sha3_512_prehash_shake_128f,
    ("slh_dsa") SlhDsaSha3512PrehashShake192s: OQS_SIG_alg_slh_dsa_sha3_512_prehash_shake_192s,
    ("slh_dsa") SlhDsaSha3512PrehashShake192f: OQS_SIG_alg_slh_dsa_sha3_512_prehash_shake_192f,
    ("slh_dsa") SlhDsaSha3512PrehashShake256s: OQS_SIG_alg_slh_dsa_sha3_512_prehash_shake_256s,
    ("slh_dsa") SlhDsaSha3512PrehashShake256f: OQS_SIG_alg_slh_dsa_sha3_512_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake128PrehashSha2128s: OQS_SIG_alg_slh_dsa_shake_128_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake128PrehashSha2128f: OQS_SIG_alg_slh_dsa_shake_128_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake128PrehashSha2192s: OQS_SIG_alg_slh_dsa_shake_128_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake128PrehashSha2192f: OQS_SIG_alg_slh_dsa_shake_128_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake128PrehashSha2256s: OQS_SIG_alg_slh_dsa_shake_128_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake128PrehashSha2256f: OQS_SIG_alg_slh_dsa_shake_128_prehash_sha2_256f,
    ("slh_dsa") SlhDsaShake128PrehashShake128s: OQS_SIG_alg_slh_dsa_shake_128_prehash_shake_128s,
    ("slh_dsa") SlhDsaShake128PrehashShake128f: OQS_SIG_alg_slh_dsa_shake_128_prehash_shake_128f,
    ("slh_dsa") SlhDsaShake128PrehashShake192s: OQS_SIG_alg_slh_dsa_shake_128_prehash_shake_192s,
    ("slh_dsa") SlhDsaShake128PrehashShake192f: OQS_SIG_alg_slh_dsa_shake_128_prehash_shake_192f,
    ("slh_dsa") SlhDsaShake128PrehashShake256s: OQS_SIG_alg_slh_dsa_shake_128_prehash_shake_256s,
    ("slh_dsa") SlhDsaShake128PrehashShake256f: OQS_SIG_alg_slh_dsa_shake_128_prehash_shake_256f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake256PrehashSha2128s: OQS_SIG_alg_slh_dsa_shake_256_prehash_sha2_128s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake256PrehashSha2128f: OQS_SIG_alg_slh_dsa_shake_256_prehash_sha2_128f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake256PrehashSha2192s: OQS_SIG_alg_slh_dsa_shake_256_prehash_sha2_192s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake256PrehashSha2192f: OQS_SIG_alg_slh_dsa_shake_256_prehash_sha2_192f,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake256PrehashSha2256s: OQS_SIG_alg_slh_dsa_shake_256_prehash_sha2_256s,
    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]
    ("slh_dsa") SlhDsaShake256PrehashSha2256f: OQS_SIG_alg_slh_dsa_shake_256_prehash_sha2_256f,
    ("slh_dsa") SlhDsaShake256PrehashShake128s: OQS_SIG_alg_slh_dsa_shake_256_prehash_shake_128s,
    ("slh_dsa") SlhDsaShake256PrehashShake128f: OQS_SIG_alg_slh_dsa_shake_256_prehash_shake_128f,
    ("slh_dsa") SlhDsaShake256PrehashShake192s: OQS_SIG_alg_slh_dsa_shake_256_prehash_shake_192s,
    ("slh_dsa") SlhDsaShake256PrehashShake192f: OQS_SIG_alg_slh_dsa_shake_256_prehash_shake_192f,
    ("slh_dsa") SlhDsaShake256PrehashShake256s: OQS_SIG_alg_slh_dsa_shake_256_prehash_shake_256s,
    ("slh_dsa") SlhDsaShake256PrehashShake256f: OQS_SIG_alg_slh_dsa_shake_256_prehash_shake_256f,
}
