#!/usr/bin/env python3

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "oqs-sys/liboqs/src/sig/sig.h"
CARGO_TOML = ROOT / "oqs/Cargo.toml"
OUTPUT = ROOT / "oqs/src/generated_sig_algorithms.rs"


def rust_variant(symbol: str) -> str:
    prefix = "OQS_SIG_alg_"
    if not symbol.startswith(prefix):
        raise ValueError(f"unexpected signature symbol: {symbol}")

    parts = symbol.removeprefix(prefix).split("_")

    def convert(part: str) -> str:
        if all(c.isupper() or c.isdigit() for c in part):
            return part
        return part[:1].upper() + part[1:]

    return "".join(convert(part) for part in parts)


def supported_signature_features():
    text = CARGO_TOML.read_text()

    match = re.search(
        r'^sigs\s*=\s*\[(.*?)\]',
        text,
        re.MULTILINE,
    )
    if not match:
        raise RuntimeError("could not find sigs feature in oqs/Cargo.toml")

    return [
        item.strip().strip('"')
        for item in match.group(1).split(",")
        if item.strip() and not item.strip().startswith('"oqs-sys/')
    ]


def signature_feature(symbol: str, features):
    suffix = symbol.removeprefix("OQS_SIG_alg_")

    for feature in sorted(features, key=len, reverse=True):
        if not suffix.startswith(feature + "_"):
            continue

        # ML-DSA extmu expects an externally computed 64-byte mu value
        # rather than an arbitrary message, so keep it separate from the
        # ordinary message-signing Rust API.
        if feature == "ml_dsa" and suffix.endswith("_extmu"):
            return None

        return feature

    return None


def main():
    features = supported_signature_features()
    algorithms = []

    for line in HEADER.read_text().splitlines():
        line = line.strip()

        if not line.startswith("#define OQS_SIG_alg_"):
            continue

        fields = line.split()
        if len(fields) < 3:
            continue

        symbol = fields[1]
        feature = signature_feature(symbol, features)

        if feature is None:
            continue

        algorithms.append((feature, rust_variant(symbol), symbol))

    if not algorithms:
        raise RuntimeError("no supported signature algorithms found")

    lines = [
        "// @generated by scripts/generate_sig_algorithms.py",
        "// Source: oqs-sys/liboqs/src/sig/sig.h",
        "// Do not edit manually.",
        "",
        "implement_sigs! {",
    ]

    for feature, variant, symbol in algorithms:
        if (
            symbol.startswith("OQS_SIG_alg_slh_dsa_pure_sha2_")
            or "_prehash_sha2_" in symbol
        ):
            lines.append(
                '    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]'
            )

        lines.append(f'    ("{feature}") {variant}: {symbol},')

    lines.append("}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
