#!/usr/bin/env python3

from pathlib import Path

# Generate the signature algorithms currently exposed by the Rust wrapper.
# Additional liboqs variants are intentionally excluded until they are
# explicitly supported by the wrapper API.

ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "oqs-sys/liboqs/src/sig/sig.h"
OUTPUT = ROOT / "oqs/src/generated_sig_algorithms.rs"

FEATURE_ORDER = [
    "cross",
    "falcon",
    "mayo",
    "ml_dsa",
    "slh_dsa",
    "uov",
]

SLH_DSA_ORDER = [
    "OQS_SIG_alg_slh_dsa_pure_sha2_128f",
    "OQS_SIG_alg_slh_dsa_pure_sha2_128s",
    "OQS_SIG_alg_slh_dsa_pure_sha2_192f",
    "OQS_SIG_alg_slh_dsa_pure_sha2_192s",
    "OQS_SIG_alg_slh_dsa_pure_sha2_256f",
    "OQS_SIG_alg_slh_dsa_pure_sha2_256s",
    "OQS_SIG_alg_slh_dsa_pure_shake_128f",
    "OQS_SIG_alg_slh_dsa_pure_shake_128s",
    "OQS_SIG_alg_slh_dsa_pure_shake_192f",
    "OQS_SIG_alg_slh_dsa_pure_shake_192s",
    "OQS_SIG_alg_slh_dsa_pure_shake_256f",
    "OQS_SIG_alg_slh_dsa_pure_shake_256s",
]


def rust_variant(symbol: str) -> str:
    prefix = "OQS_SIG_alg_"
    if not symbol.startswith(prefix):
        raise ValueError(f"unexpected signature symbol: {symbol}")

    parts = symbol.removeprefix(prefix).split("_")

    def convert(part: str) -> str:
        if all(c.isupper() or c.isdigit() for c in part):
            return part
        return part[:1].upper() + part[1:]

    return "".join(convert(part) for part in parts)


def signature_feature(symbol: str):
    if symbol.startswith("OQS_SIG_alg_cross_"):
        return "cross"
    if symbol.startswith("OQS_SIG_alg_falcon_"):
        return "falcon"
    if symbol.startswith("OQS_SIG_alg_mayo_"):
        return "mayo"
    if symbol.startswith("OQS_SIG_alg_ml_dsa_") and not symbol.endswith("_extmu"):
        return "ml_dsa"
    if symbol.startswith("OQS_SIG_alg_slh_dsa_pure_"):
        return "slh_dsa"
    if symbol.startswith("OQS_SIG_alg_uov_"):
        return "uov"
    return None


def sort_key(entry):
    feature, _, symbol = entry
    family_order = FEATURE_ORDER.index(feature)

    if feature == "slh_dsa":
        algorithm_order = SLH_DSA_ORDER.index(symbol)
    else:
        algorithm_order = 0

    return family_order, algorithm_order


def main():
    algorithms = []

    for line in HEADER.read_text().splitlines():
        line = line.strip()

        if not line.startswith("#define OQS_SIG_alg_"):
            continue

        fields = line.split()
        if len(fields) < 3:
            continue

        symbol = fields[1]
        feature = signature_feature(symbol)

        if feature is None:
            continue

        algorithms.append((feature, rust_variant(symbol), symbol))

    algorithms.sort(key=sort_key)

    if len(algorithms) != 53:
        raise RuntimeError(
            f"expected 53 currently exposed signature algorithms, got {len(algorithms)}"
        )

    lines = [
        "// @generated by scripts/generate_sig_algorithms.py",
        "// Source: oqs-sys/liboqs/src/sig/sig.h",
        "// Do not edit manually.",
        "",
        "implement_sigs! {",
    ]

    for feature, variant, symbol in algorithms:
        if symbol.startswith("OQS_SIG_alg_slh_dsa_pure_sha2_"):
            lines.append(
                '    #[cfg_attr(windows, ignore = "SLH-DSA SHA-2 signing currently fails on the windows-latest MSVC runner")]'
            )

        lines.append(f'    ("{feature}") {variant}: {symbol},')

    lines.append("}")
    lines.append("")

    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
